# Generated by Django 5.1.6 on 2025-02-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipulador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuser',
            name='file_name',
            field=models.CharField(default='file.jsonl', max_length=255),
            preserve_default=False,
        ),
    ]
